apiVersion: openliberty.io/v1beta1
kind: OpenLibertyApplication
metadata:
  name: tekton-app
spec:
  applicationImage: image-registry.openshift-image-registry.svc:5000/e2e/app:latest
  env:
    - name: WLP_LOGGING_CONSOLE_FORMAT
      value: "basic"
    - name: MQ_HOST_NAME
      value: "mq-server-ibm-mq.ibm-mq.svc"
    - name: MQ_QUEUE_MANAGER
      value: "mqserver"
  expose: true
  service:
    type: ClusterIP
    port: 9080
